name = "Additive"
author = "Rafifos"
version = "1.35.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8cd564e13dbf4efde78b91643da121d8f84100aa14ad9ea4c71628ee8778e5b5"

[versions]
fabric = "0.16.10"
minecraft = "1.21.5"
