name = "Frends"
author = "Rafifos"
version = "1.35.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76aa7bf4e1c33a043d4dcbd70e248e1a98b9954c3f900ff98f864f0843d54507"

[versions]
fabric = "0.16.13"
minecraft = "1.21.5"
