name = "Frends"
author = "Rafifos"
version = "1.35.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f9e145baac7014255db43e86c1a87c8d16be41dab0a2965d75f6918a95e303e"

[versions]
fabric = "0.16.13"
minecraft = "1.21.5"
