name = "Frends"
author = "Rafifos"
version = "1.35.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "becaf826fadd60ef67b755cdd177d6ee9694a5fc7953753ac598d5f80e24a883"

[versions]
fabric = "0.16.13"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21.4"]
