name = "Frends"
author = "Rafifos"
version = "1.35.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02aff45c45ac00d8cc9676c6527d1d83c23f72589914b7d1d5990060aa4988f0"

[versions]
fabric = "0.16.13"
minecraft = "1.21.5"
