author      = "Rafifos"
name        = "Frends"
pack-format = "packwiz:1.1.0"
version     = "1.35.0+1.21.5.fabric"

[index]
 file        = "index.toml"
 hash        = "7885e91212ff4a72cba08f1f2eeab021c8da4adea4cfcd72fc49c0dd06188f04"
 hash-format = "sha256"

[versions]
 fabric    = "0.16.13"
 minecraft = "1.21.5"
