name = "Frends"
author = "Rafifos"
version = "1.35.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6581287d640f32c661abe9bc63b85ec73070cd3047286ddc56c7698a7c461e00"

[versions]
fabric = "0.16.13"
minecraft = "1.21.5"
