name = "Frends"
author = "Rafifos"
version = "1.35.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4507a7b21fe6aa91c67e5cabc57645004540f3220fcfc0e4d75070597ae3d0d"

[versions]
fabric = "0.16.13"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21.4"]
