name = "Additive"
author = "SkywardMC"
version = "1.35.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a9d5c38eda981526eec243061fb091807ad4693a47e93e66526efa520a4c655"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
