name = "Additive"
author = "SkywardMC"
version = "1.35.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abe95ff16d730cf1102df417c517f00b568362bbed89f26dfed4d7453929d67b"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
